In [2]:
import numpy as np

In [5]:
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0, 0, 0, 1]]).T

In [6]:
x.shape, y.shape

((4, 2), (4, 1))

In [7]:
def sigmoid(z):
    return 1/(1+ np.exp(-z))

In [11]:
#no hidden layer weights
weights = 2 * np.random.random((2, 1)) - 1
bias = 2 * np.random.random(1) - 1
weights, bias

(array([[-0.26707198],
        [-0.67391754]]),
 array([-0.0662064]))

In [12]:
#forward propagation without any hidden layer
output0 = x
output = sigmoid(np.dot(output0, weights) + bias)
output

array([[0.48345444],
       [0.32297704],
       [0.41744316],
       [0.26752897]])

In [16]:
#if we have some hidden layers -> let's take 1 hidden layer
wh = 2 * np.random.random((2, 2)) - 1
bh = 2 * np.random.random((1, 2)) - 1
wo = 2 * np.random.random((2, 1)) - 1
bo = 2 * np.random.random((1, 1)) - 1
wh, bh, wo, bo

(array([[-0.28240902,  0.71411095],
        [ 0.09705537, -0.13288772]]),
 array([[0.61963406, 0.7460681 ]]),
 array([[-0.74922574],
        [ 0.87810386]]),
 array([[0.78215782]]))

In [18]:
output0 = x
outputHidden = sigmoid(np.dot(output0, wh) + bh)
output = sigmoid(np.dot(outputHidden, wo) + bo)
outputHidden, output

(array([[0.65013532, 0.67832136],
        [0.67187759, 0.64866595],
        [0.5835163 , 0.81156006],
        [0.60689533, 0.79039224]]),
 array([[0.70903384],
        [0.70022424],
        [0.74223286],
        [0.7352652 ]]))